FROM pytorch/pytorch:2.4.0-cuda12.1-cudnn8-runtime
ENV PIP_NO_CACHE_DIR=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .

RUN pip install -U pip && pip install .

ENV DREAMSCRIBBLES_PORT=7860
EXPOSE 7860
CMD ["python", "-m", "dreamscribbles"]
